#! validate-crd: deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: awss3operator.0.1.0
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    categories: Provisioning
    description: Manage the full lifecycle of installing, configuring and managing AWS S3 Provisioner.
    containerImage: quay.io/screeley44/aws-s3-provisioner:v1.0.0
    createdAt: 2019-05-02T16:12:00Z
    repository: https://github.com/yard-turkey/aws-s3-operator
    certified: "false"
    support: OCTO
spec:
  displayName: AWS S3 Operator
  description: |
    AWS S3 Operator will deploy the AWS S3 Provisioner - more to be added

  keywords: ['awss3provisioner', 'aws', 'S3', 'provisioner', 'buckets']

  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com

  provider:
    name: Red Hat

  links:
  - name: AWS S3 Provisioner
    url: https://github.com/yard-turkey/aws-s3-provisioner
  - name: Documentation
    url: https://github.com/yard-turkey/aws-s3-olm-operator

  labels:
    alm-status-descriptors: awss3operator.0.1.0
    alm-owner-awss3: awss3operator

  selector:
    matchLabels:
      alm-owner-awss3: awss3operator

  icon:
  - base64data: PHN2ZyB3aWR0aD0iMjQ5MCIgaGVpZ2h0PSIyNTAwIiB2aWV3Qm94PSIwIDAgMjU2IDI1NyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTEyOC4wMDEuNjY3QzU3LjMxMS42NjcgMCA1Ny45NzEgMCAxMjguNjY0YzAgNzAuNjkgNTcuMzExIDEyNy45OTggMTI4LjAwMSAxMjcuOTk4UzI1NiAxOTkuMzU0IDI1NiAxMjguNjY0QzI1NiA1Ny45NyAxOTguNjg5LjY2NyAxMjguMDAxLjY2N3ptMCAyMzkuNTZjLTIwLjExMiAwLTM2LjQxOS0xMy40MzUtMzYuNDE5LTMwLjAwNGg3Mi44MzhjMCAxNi41NjYtMTYuMzA2IDMwLjAwNC0zNi40MTkgMzAuMDA0em02MC4xNTMtMzkuOTRINjcuODQyVjE3OC40N2gxMjAuMzE0djIxLjgxNmgtLjAwMnptLS40MzItMzMuMDQ1SDY4LjE4NWMtLjM5OC0uNDU4LS44MDQtLjkxLTEuMTg4LTEuMzc1LTEyLjMxNS0xNC45NTQtMTUuMjE2LTIyLjc2LTE4LjAzMi0zMC43MTYtLjA0OC0uMjYyIDE0LjkzMyAzLjA2IDI1LjU1NiA1LjQ1IDAgMCA1LjQ2NiAxLjI2NSAxMy40NTggMi43MjItNy42NzMtOC45OTQtMTIuMjMtMjAuNDI4LTEyLjIzLTMyLjExNiAwLTI1LjY1OCAxOS42OC00OC4wNzkgMTIuNTgtNjYuMjAxIDYuOTEuNTYyIDE0LjMgMTQuNTgzIDE0LjggMzYuNTA1IDcuMzQ2LTEwLjE1MiAxMC40Mi0yOC42OSAxMC40Mi00MC4wNTYgMC0xMS43NjkgNy43NTUtMjUuNDQgMTUuNTEyLTI1LjkwNy02LjkxNSAxMS4zOTYgMS43OSAyMS4xNjUgOS41MyA0NS40IDIuOTAyIDkuMTAzIDIuNTMyIDI0LjQyMyA0Ljc3MiAzNC4xMzguNzQ0LTIwLjE3OCA0LjIxMy00OS42MiAxNy4wMTQtNTkuNzg0LTUuNjQ3IDEyLjguODM2IDI4LjgxOCA1LjI3IDM2LjUxOCA3LjE1NCAxMi40MjQgMTEuNDkgMjEuODM2IDExLjQ5IDM5LjYzOCAwIDExLjkzNi00LjQwNyAyMy4xNzMtMTEuODQgMzEuOTU4IDguNDUyLTEuNTg2IDE0LjI4OS0zLjAxNiAxNC4yODktMy4wMTZsMjcuNDUtNS4zNTVjLjAwMi0uMDAyLTMuOTg3IDE2LjQwMS0xOS4zMTQgMzIuMTk3eiIgZmlsbD0iI0RBNEUzMSIvPjwvc3ZnPg==
    mediatype: image/svg+xml

  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false

  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: aws-s3
        rules:
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - "*"
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - events
          - secrets
          - configmaps
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
           verbs:
          - "*"
      deployments:
      - name: aws-s3-provisioner
        spec:
          replicas: 1
          selector:
            matchLabels:
              k8s-app: aws-s3-provisioner
          template:
            metadata:
              labels:
                k8s-app: aws-s3-provisioner
            spec:
              serviceAccount: aws-s3-provisioner-0-1-0
              containers:
              - name: aws-s3-provisioner
                image: quay.io/screeley44/aws-s3-provsioner:v1.0.0
  maturity: alpha
  version: 0.1.0
  customresourcedefinitions:
    owned:
    - name: objectbuckets.objectbucket.io
      version: v1alpha1
      kind: ObjectBucket
      displayName: Object Bucket
      description: instance of an AWS S3 Bucket
    - name: objectbucketclaims.objectbucket.io
      version: v1alpha1
      kind: ObjectBucketClaim
      displayName: Object Bucket Claim
      description: Request for an AWS S3 Bucket
