apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: community-operators
  namespace: openshift-marketplace
spec:
  type: appregistry
#  endpoint: https://quay.io/cnr
  endpoint: https://quay.io/screeley44/aws-s3-operator-registry
  registryNamespace: openshift-marketplace
  displayName: "Community Operators"
  publisher: "Red Hat"
