apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aws-s3-operator-subscription
  namespace: s3-provisioner
spec:
  source: awss3operator
  sourceNamespace: openshift-operator-lifecycle-manager
  name: awss3operator
  startingCSV: awss3operator.0.1.0
  channel: alpha
